# Generated by Django 4.2.7 on 2025-11-24 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=200)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'observed_at'], name='observation_latitud_100be9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('intensity', models.IntegerField(help_text='Number of vehicles')),
                ('occupancy', models.FloatField(help_text='Percentage 0-100')),
                ('average_speed', models.FloatField(help_text='km/h')),
                ('congestion_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=50)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'observed_at'], name='observation_latitud_71da12_idx')],
            },
        ),
        migrations.CreateModel(
            name='AirQualityObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'observed_at'], name='observation_latitud_71518d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('observed_property', models.CharField(max_length=200)),
                ('result_value', models.FloatField()),
                ('result_unit', models.CharField(blank=True, max_length=50)),
                ('result_string', models.TextField(blank=True)),
                ('phenomenon_time', models.DateTimeField()),
                ('result_time', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-result_time'],
                'indexes': [models.Index(fields=['sensor', 'result_time'], name='observation_sensor__ea74e2_idx'), models.Index(fields=['observed_property', 'result_time'], name='observation_observe_291684_idx')],
            },
        ),
    ]
