# Generated by Django 4.2.7 on 2025-11-24 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('pressure', 'Pressure Sensor'), ('pm25', 'PM2.5 Sensor'), ('pm10', 'PM10 Sensor'), ('no2', 'NO2 Sensor'), ('o3', 'O3 Sensor'), ('co', 'CO Sensor'), ('so2', 'SO2 Sensor'), ('noise', 'Noise Sensor'), ('traffic', 'Traffic Sensor'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('observes_property', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deployed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.platform')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
    ]
