# Generated by Django 4.2.7 on 2025-11-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userdevice_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin as trusted device'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
