# Generated by Django 4.2.7 on 2025-11-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdevice_is_verified_userdevice_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='API key (auto-generated)', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Vô hiệu hóa key nếu bị lộ')),
                ('device', models.OneToOneField(help_text='Thiết bị sở hữu API key này', on_delete=django.db.models.deletion.CASCADE, related_name='device_api_key', to='accounts.userdevice')),
            ],
            options={
                'verbose_name': 'Device API Key',
                'verbose_name_plural': 'Device API Keys',
                'db_table': 'device_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
