# Generated by Django 4.2.7 on 2025-12-10 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(help_text='NGSI-LD entity ID', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(default='Ho Chi Minh', max_length=100)),
                ('station_type', models.CharField(choices=[('bus_stop', 'Bus Stop'), ('bus_terminal', 'Bus Terminal'), ('metro_station', 'Metro Station')], default='bus_stop', max_length=50)),
                ('routes', models.JSONField(default=list, help_text='List of bus routes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('has_shelter', models.BooleanField(default=True)),
                ('has_bench', models.BooleanField(default=True)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('has_real_time_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(default='Ho Chi Minh', max_length=100)),
                ('parking_type', models.CharField(choices=[('on_street', 'On Street'), ('off_street', 'Off Street'), ('parking_lot', 'Parking Lot'), ('parking_garage', 'Parking Garage')], default='on_street', max_length=50)),
                ('total_spaces', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='open', max_length=20)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_disability_spaces', models.BooleanField(default=True)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_24h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('road_name', models.CharField(max_length=255)),
                ('road_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(default='Ho Chi Minh', max_length=100)),
                ('congestion_level', models.CharField(choices=[('free', 'Free'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('severe', 'Severe')], default='free', max_length=20)),
                ('average_speed', models.FloatField(help_text='km/h')),
                ('vehicle_count', models.IntegerField(default=0)),
                ('occupancy', models.FloatField(default=0.0)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('roadwork', 'Road Work'), ('congestion', 'Congestion'), ('weather', 'Weather'), ('event', 'Event'), ('other', 'Other')], default='accident', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(default='Ho Chi Minh', max_length=100)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
