# Generated by Django 4.2.7 on 2025-12-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên provider (vd: OpenWeatherMap)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Slug để identify (vd: openweathermap)', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('weather', 'Thời tiết'), ('air_quality', 'Chất lượng không khí'), ('traffic', 'Giao thông'), ('maps', 'Bản đồ'), ('notifications', 'Thông báo'), ('other', 'Khác')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Mô tả về provider')),
                ('base_url', models.URLField(help_text='Base URL của API (vd: https://api.openweathermap.org)')),
                ('documentation_url', models.URLField(blank=True, help_text='Link tài liệu API')),
                ('auth_type', models.CharField(choices=[('api_key_query', 'API Key trong Query Params'), ('api_key_header', 'API Key trong Header'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('oauth2', 'OAuth 2.0'), ('none', 'Không cần xác thực')], default='api_key_query', max_length=50)),
                ('auth_key_name', models.CharField(blank=True, help_text='Tên param/header cho API key (vd: appid, X-API-Key)', max_length=100)),
                ('default_headers', models.JSONField(blank=True, default=dict, help_text='Headers mặc định (JSON)')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Số request tối đa mỗi phút')),
                ('rate_limit_per_day', models.IntegerField(default=1000, help_text='Số request tối đa mỗi ngày')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Yêu cầu subscription trả phí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External API Provider',
                'verbose_name_plural': 'External API Providers',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_encrypted_key', models.BinaryField(db_column='encrypted_key')),
                ('_encrypted_credentials', models.BinaryField(blank=True, db_column='encrypted_credentials', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_user_override', models.BooleanField(default=True, help_text='Cho phép user dùng key riêng thay vì key hệ thống')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_key', to='integrations.externalapiprovider')),
            ],
            options={
                'verbose_name': 'System API Key',
                'verbose_name_plural': 'System API Keys',
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_encrypted_key', models.BinaryField(db_column='encrypted_key')),
                ('_encrypted_credentials', models.BinaryField(blank=True, db_column='encrypted_credentials', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keys', to='integrations.externalapiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
